GET http://localhost:3000/user/index?a=333 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlpUMTEiLCJlbWFpbCI6IjEyZDExZGRzZGZzM2ZmZkBxcS5jb20iLCJpYXQiOjE3MjY1NjA3ODQsImV4cCI6MTcyNzE2NTU4NH0.611MBxEpQO9ehbU9Zb9skLFyU211E9JuWQPA1E-Iz4g


# POST http://localhost:3000/user/create HTTP/1.1
# Content-Type: application/json

# {
#     "name":"ZT11",
#     "email":"12d11ddsdfs3fff@qq.com"
# }